# Generated by Django 4.2.5 on 2023-12-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0004_heroimages_remove_openaccount_mothersname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
