# Generated by Django 4.1.5 on 2023-09-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0005_heroimages_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroimages',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='heroimages',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='heroimages',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='heroimages',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='heroimages',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='heroimages',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='heroimages',
            name='image7',
        ),
    ]
