# Generated by Django 4.1.5 on 2024-01-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0005_remove_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='aadharimg',
            field=models.CharField(blank=True, default='path/to/default/image.jpg', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='panimg',
            field=models.ImageField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='user_pan_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='user_photos/'),
        ),
    ]
