# Generated by Django 4.1.5 on 2023-09-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0006_rename_image1_heroimages_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaccount',
            name='mothersname',
        ),
        migrations.AddField(
            model_name='applyloan',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depositetype',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openaccount',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
