# Generated by Django 4.1.5 on 2024-01-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0006_user_aadhar_user_aadharimg_user_pan_user_panimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadharimg',
            field=models.FileField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='user_aadhar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='panimg',
            field=models.FileField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='user_pan_cards/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='user_photos/'),
        ),
    ]
