# Generated by Django 4.1.5 on 2024-01-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0007_alter_user_aadharimg_alter_user_panimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
