# Generated by Django 4.1.5 on 2023-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0007_remove_openaccount_mothersname_applyloan_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
