# Generated by Django 4.1.5 on 2024-01-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0008_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadharimg',
            field=models.FileField(blank=True, null=True, upload_to='user_aadhar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='panimg',
            field=models.FileField(blank=True, null=True, upload_to='user_pan_cards/'),
        ),
    ]
