# Generated by Django 4.1.5 on 2023-09-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0009_alter_heroimages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimages',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
